In [1]:
import pandas as pd
from mordred import Calculator, descriptors
from rdkit import Chem
from rdkit.Chem import AllChem

In [22]:
df=pd.read_csv(r"C:\Users\19189\Desktop\Catmos.csv")

In [23]:
df

,Unnamed: 0,ChemID,CASRN,Name,CATMoS_LD50_mgkg,Canonical_QSARr,Molecule,Morgan2FPs,LogLD50,MACCSFPs
0,0,2,68523-18-2,Fenpirithrin,460.00,CC1(C)C(C1C=C(Cl)Cl)C(=O)OC(C#N)C1C=CC=C(N=1)O...,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],2.662758,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1...
1,1,3,88-04-0,"4-Chloro-3,5-dimethylphenol",3830.00,CC1C=C(O)C=C(C)C=1Cl,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],3.583199,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
2,2,4,603-50-9,Bisacodyl,4305.00,CC(=O)OC1C=CC(=CC=1)C(C1C=CC=CN=1)C1C=CC(=CC=1...,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],3.633973,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
3,3,5,120-36-5,Dichlorprop,689.00,CC(OC1C=CC(Cl)=CC=1Cl)C(O)=O,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],2.838219,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
4,4,6,103-26-4,Methyl cinnamate,2610.00,COC(=O)C=CC1C=CC=CC=1,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],3.416641,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
...,...,...,...,...,...,...,...,...,...,...
11982,11982,53140,996-04-3,"Phosphonodithioic acid, methyl-, S,S-dipropyl ...",1.78,CP(=O)(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 2 0 0],0.250420,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
11983,11983,53141,996-05-4,"Phosphonotrithioic acid, methyl-, dipropyl ester",18.00,CP(=S)(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 2 0 0],1.255273,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
11984,11984,53145,99784-08-4,NaN,7500.00,COC1C=CC(=CC=1O)C1COC2=CC=CC=C2O1,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],3.875061,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
11985,11985,53146,99874-01-8,"L-Cysteine, N-(2-mercapto-2-methyl-1-oxopropyl...",5220.00,CC(C)(S)C(=O)NC(CS)C(O)=O,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],3.717671,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
11986,11986,53147,999-34-8,"Phosphonodithious acid, methyl-, dipropyl ester",2.24,CP(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],0.350248,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...

In [4]:
def All_Mordred_descriptors(data):
    calc = Calculator(descriptors, ignore_3D=False)
    mols = [Chem.MolFromSmiles(smi) for smi in data]
    df = calc.pandas(mols)
    return df

In [5]:
mordred_descriptors = All_Mordred_descriptors(df['Canonical_QSARr'])

  1%|▍                                                                              | 68/11987 [00:05<11:21, 17.50it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  6%|████▎                                                                         | 672/11987 [00:22<06:35, 28.65it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  7%|█████▎                                                                        | 816/11987 [00:26<04:08, 44.99it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  8%|██████▍                                                                      | 1008/11987 [00:31<04:25, 41.31it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 11%|████████▎                                                                    | 1299/11987 [00:40<03:58, 44.88it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 17%|████████████▊                                                                | 2002/11987 [01:00<03:36, 46.12it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 19%|██████████████▎                                                              | 2228/11987 [01:09<11:54, 13.65it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 20%|███████████████                                                              | 2340/11987 [01:14<07:51, 20.46it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 20%|███████████████▌                                                             | 2415/11987 [01:16<08:31, 18.70it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 21%|████████████████▎                                                            | 2534/11987 [01:21<05:51, 26.90it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 22%|█████████████████▏                                                           | 2678/11987 [01:27<06:33, 23.64it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 24%|██████████████████▏                                                          | 2834/11987 [01:32<06:14, 24.46it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 26%|████████████████████▎                                                        | 3158/11987 [01:46<05:17, 27.77it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 28%|█████████████████████▌                                                       | 3355/11987 [01:50<02:24, 59.73it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 30%|██████████████████████▊                                                      | 3543/11987 [01:55<04:11, 33.52it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 40%|██████████████████████████████▊                                              | 4801/11987 [02:26<02:00, 59.59it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 89%|███████████████████████████████████████████████████████████████████▋        | 10670/11987 [06:14<03:20,  6.55it/s]

D:\anaconda3\envs\CATMOS\Lib\site-packages\mordred\_matrix_attributes.py:251: RuntimeWarning: invalid value encountered in scalar power
  s += (eig.vec[i, eig.max] * eig.vec[j, eig.max]) ** -0.5

100%|████████████████████████████████████████████████████████████████████████████| 11987/11987 [07:11<00:00, 27.77it/s]

In [6]:
mordred_descriptors

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,34.992970,2.613976,4.943050,34.992970,1.249749,4.277221,...,10.344674,84.588084,416.069448,9.044988,2244,39,146.0,172.0,10.201389,6.166667
1,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,11.643052,2.307250,4.614501,11.643052,1.164305,3.206363,...,9.078065,39.748909,156.034193,8.212326,110,13,48.0,54.0,4.944444,2.222222
2,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,34.387058,2.415622,4.831244,34.387058,1.273595,4.209906,...,10.045811,61.772145,361.131408,7.850683,1954,39,136.0,155.0,8.638889,6.000000
3,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,1,0,16.532794,2.301365,4.602730,16.532794,1.180914,3.526944,...,9.254262,45.062973,233.985049,10.635684,316,18,66.0,73.0,6.555556,3.138889
4,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,15.354433,2.172565,4.345130,15.354433,1.279536,3.360730,...,8.688622,41.277218,162.068080,7.366731,226,12,52.0,55.0,4.222222,2.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11982,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,12.592066,2.188901,4.377802,12.592066,1.144733,3.228506,...,8.586906,39.549123,212.045844,7.573066,180,10,44.0,44.0,5.5625,2.750000
11983,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,12.592066,2.188901,4.377802,12.592066,1.144733,3.228506,...,8.586906,39.549123,228.023000,8.143679,180,10,44.0,44.0,5.5625,2.750000
11984,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,25.276144,2.403626,4.807252,25.276144,1.330323,3.885631,...,9.883948,52.530255,258.089209,7.820885,720,30,100.0,118.0,5.416667,4.250000
11985,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,1,0,13.983995,2.272120,4.544240,13.983995,1.075692,3.416091,...,9.131838,43.455545,223.033685,8.578219,256,16,58.0,62.0,7.895833,2.944444
11986,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,11.918006,2.028523,4.057047,11.918006,1.191801,3.114674,...,7.878155,36.593370,196.050929,7.261146,149,8,36.0,35.0,4.611111,2.666667

In [24]:
df=pd.concat([df,df2],axis=1)

In [27]:
df=df.drop('Unnamed: 0',axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

In [28]:
df=df.drop('ChemID',axis=1)
df

,CASRN,Name,CATMoS_LD50_mgkg,Canonical_QSARr,Molecule,Morgan2FPs,LogLD50,MACCSFPs,ABC,ABCGG,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,68523-18-2,Fenpirithrin,460.00,CC1(C)C(C1C=C(Cl)Cl)C(=O)OC(C#N)C1C=CC=C(N=1)O...,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],2.662758,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1...,0.0,0.0,...,10.344674,84.588084,416.069448,9.044988,2244,39,146.0,172.0,10.201389,6.166667
1,88-04-0,"4-Chloro-3,5-dimethylphenol",3830.00,CC1C=C(O)C=C(C)C=1Cl,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],3.583199,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,9.078065,39.748909,156.034193,8.212326,110,13,48.0,54.0,4.944444,2.222222
2,603-50-9,Bisacodyl,4305.00,CC(=O)OC1C=CC(=CC=1)C(C1C=CC=CN=1)C1C=CC(=CC=1...,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],3.633973,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,10.045811,61.772145,361.131408,7.850683,1954,39,136.0,155.0,8.638889,6.000000
3,120-36-5,Dichlorprop,689.00,CC(OC1C=CC(Cl)=CC=1Cl)C(O)=O,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],2.838219,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,9.254262,45.062973,233.985049,10.635684,316,18,66.0,73.0,6.555556,3.138889
4,103-26-4,Methyl cinnamate,2610.00,COC(=O)C=CC1C=CC=CC=1,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],3.416641,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,8.688622,41.277218,162.068080,7.366731,226,12,52.0,55.0,4.222222,2.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11982,996-04-3,"Phosphonodithioic acid, methyl-, S,S-dipropyl ...",1.78,CP(=O)(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 2 0 0],0.250420,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,8.586906,39.549123,212.045844,7.573066,180,10,44.0,44.0,5.562500,2.750000
11983,996-05-4,"Phosphonotrithioic acid, methyl-, dipropyl ester",18.00,CP(=S)(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 2 0 0],1.255273,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,8.586906,39.549123,228.023000,8.143679,180,10,44.0,44.0,5.562500,2.750000
11984,99784-08-4,NaN,7500.00,COC1C=CC(=CC=1O)C1COC2=CC=CC=C2O1,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],3.875061,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,9.883948,52.530255,258.089209,7.820885,720,30,100.0,118.0,5.416667,4.250000
11985,99874-01-8,"L-Cysteine, N-(2-mercapto-2-methyl-1-oxopropyl...",5220.00,CC(C)(S)C(=O)NC(CS)C(O)=O,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 1 0 ... 0 0 0],3.717671,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,9.131838,43.455545,223.033685,8.578219,256,16,58.0,62.0,7.895833,2.944444
11986,999-34-8,"Phosphonodithious acid, methyl-, dipropyl ester",2.24,CP(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,[0 0 0 ... 0 0 0],0.350248,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.0,0.0,...,7.878155,36.593370,196.050929,7.261146,149,8,36.0,35.0,4.611111,2.666667

In [29]:
df=df.drop('Morgan2FPs',axis=1)
df=df.drop('MACCSFPs',axis=1)
df

,CASRN,Name,CATMoS_LD50_mgkg,Canonical_QSARr,Molecule,LogLD50,ABC,ABCGG,nAcid,nBase,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,68523-18-2,Fenpirithrin,460.00,CC1(C)C(C1C=C(Cl)Cl)C(=O)OC(C#N)C1C=CC=C(N=1)O...,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,2.662758,0.0,0.0,0,0,...,10.344674,84.588084,416.069448,9.044988,2244,39,146.0,172.0,10.201389,6.166667
1,88-04-0,"4-Chloro-3,5-dimethylphenol",3830.00,CC1C=C(O)C=C(C)C=1Cl,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,3.583199,0.0,0.0,0,0,...,9.078065,39.748909,156.034193,8.212326,110,13,48.0,54.0,4.944444,2.222222
2,603-50-9,Bisacodyl,4305.00,CC(=O)OC1C=CC(=CC=1)C(C1C=CC=CN=1)C1C=CC(=CC=1...,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,3.633973,0.0,0.0,0,0,...,10.045811,61.772145,361.131408,7.850683,1954,39,136.0,155.0,8.638889,6.000000
3,120-36-5,Dichlorprop,689.00,CC(OC1C=CC(Cl)=CC=1Cl)C(O)=O,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,2.838219,0.0,0.0,1,0,...,9.254262,45.062973,233.985049,10.635684,316,18,66.0,73.0,6.555556,3.138889
4,103-26-4,Methyl cinnamate,2610.00,COC(=O)C=CC1C=CC=CC=1,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,3.416641,0.0,0.0,0,0,...,8.688622,41.277218,162.068080,7.366731,226,12,52.0,55.0,4.222222,2.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11982,996-04-3,"Phosphonodithioic acid, methyl-, S,S-dipropyl ...",1.78,CP(=O)(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,0.250420,0.0,0.0,0,0,...,8.586906,39.549123,212.045844,7.573066,180,10,44.0,44.0,5.562500,2.750000
11983,996-05-4,"Phosphonotrithioic acid, methyl-, dipropyl ester",18.00,CP(=S)(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,1.255273,0.0,0.0,0,0,...,8.586906,39.549123,228.023000,8.143679,180,10,44.0,44.0,5.562500,2.750000
11984,99784-08-4,NaN,7500.00,COC1C=CC(=CC=1O)C1COC2=CC=CC=C2O1,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,3.875061,0.0,0.0,0,0,...,9.883948,52.530255,258.089209,7.820885,720,30,100.0,118.0,5.416667,4.250000
11985,99874-01-8,"L-Cysteine, N-(2-mercapto-2-methyl-1-oxopropyl...",5220.00,CC(C)(S)C(=O)NC(CS)C(O)=O,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,3.717671,0.0,0.0,1,0,...,9.131838,43.455545,223.033685,8.578219,256,16,58.0,62.0,7.895833,2.944444
11986,999-34-8,"Phosphonodithious acid, methyl-, dipropyl ester",2.24,CP(SCCC)SCCC,<rdkit.Chem.rdchem.Mol object at 0x0000025EF91...,0.350248,0.0,0.0,0,0,...,7.878155,36.593370,196.050929,7.261146,149,8,36.0,35.0,4.611111,2.666667

In [7]:
df2=mordred_descriptors
df2=df2.apply(pd.to_numeric,errors='coerce').fillna(0)
df2

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,0.0,0.0,0,0,34.992970,2.613976,4.943050,34.992970,1.249749,4.277221,...,10.344674,84.588084,416.069448,9.044988,2244,39,146.0,172.0,10.201389,6.166667
1,0.0,0.0,0,0,11.643052,2.307250,4.614501,11.643052,1.164305,3.206363,...,9.078065,39.748909,156.034193,8.212326,110,13,48.0,54.0,4.944444,2.222222
2,0.0,0.0,0,0,34.387058,2.415622,4.831244,34.387058,1.273595,4.209906,...,10.045811,61.772145,361.131408,7.850683,1954,39,136.0,155.0,8.638889,6.000000
3,0.0,0.0,1,0,16.532794,2.301365,4.602730,16.532794,1.180914,3.526944,...,9.254262,45.062973,233.985049,10.635684,316,18,66.0,73.0,6.555556,3.138889
4,0.0,0.0,0,0,15.354433,2.172565,4.345130,15.354433,1.279536,3.360730,...,8.688622,41.277218,162.068080,7.366731,226,12,52.0,55.0,4.222222,2.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11982,0.0,0.0,0,0,12.592066,2.188901,4.377802,12.592066,1.144733,3.228506,...,8.586906,39.549123,212.045844,7.573066,180,10,44.0,44.0,5.562500,2.750000
11983,0.0,0.0,0,0,12.592066,2.188901,4.377802,12.592066,1.144733,3.228506,...,8.586906,39.549123,228.023000,8.143679,180,10,44.0,44.0,5.562500,2.750000
11984,0.0,0.0,0,0,25.276144,2.403626,4.807252,25.276144,1.330323,3.885631,...,9.883948,52.530255,258.089209,7.820885,720,30,100.0,118.0,5.416667,4.250000
11985,0.0,0.0,1,0,13.983995,2.272120,4.544240,13.983995,1.075692,3.416091,...,9.131838,43.455545,223.033685,8.578219,256,16,58.0,62.0,7.895833,2.944444
11986,0.0,0.0,0,0,11.918006,2.028523,4.057047,11.918006,1.191801,3.114674,...,7.878155,36.593370,196.050929,7.261146,149,8,36.0,35.0,4.611111,2.666667

In [32]:
df.to_csv(r'C:\Users\19189\Desktop\mordred_descriptors.csv',index=False)